### ISSUE TITLE
Remove Yurtctl Doc

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt.io#106]
As yurtctl deleted, we should upgrade [document](https://openyurt.io/zh/docs/installation/yurtctl-convert-revert).
Related pr: https://github.com/openyurtio/openyurt/commit/4e2a6ad9ea9178b60b0aa66a54206711c13f8ae4

**Comment by rambohe-ch** [comment]
@huiwq1990 Thanks for your suggestion. 
/assign @lonelyCZ

**Comment by lonelyCZ** [comment]
Thanks @huiwq1990 , I have planed to submit a pr to fix this.
