### ISSUE TITLE
Update docs for device management

### ISSUE THREAD

**Issue by wawlian** [openyurtio/openyurt.io#118]
Update docs for device management since OpenYurt now supports EdgeX 2

**Comment by LavenderQAQ** [comment]
After `yurt-edgex-manager` is merged into openyurt, we need to update some documentation of `edgex` crd deployment in openyurt.

**Comment by rambohe-ch** [comment]
@wawlian @LavenderQAQ I think docs of device management have been uploaded at https://openyurt.io/docs/user-manuals/iot/edgex-foundry, so i will close this issue.
