### ISSUE TITLE
fix github icon on dark theme

### ISSUE THREAD

**Issue by Arhell** [openyurtio/openyurt.io#119]
![Screenshot_1](https://user-images.githubusercontent.com/26163841/175190223-3db8b53f-d339-415a-944a-2b6d9fc60b48.png)

**Comment by rambohe-ch** [comment]
@Arhell Would you like to post a pull request to fix this problem?

**Comment by Arhell** [comment]
> @Arhell Thank you for raising issue. and would you like to post a pull request to fix this problem?

sure
