### ISSUE TITLE
Manually setup yurt-tunnel: page 404

### ISSUE THREAD

**Issue by lorrielau** [openyurtio/openyurt.io#141]
In docs of installation/Manually-setup, every-version, the links to setup yurt-tunnel lead to page 404. 
Are the docs not in the right places?  [like this one here](https://openyurt.io/zh/docs/next/installation/manually-setup#%E9%83%A8%E7%BD%B2-yurt-tunnel-%E5%8F%AF%E9%80%89)

**Comment by rambohe-ch** [comment]
@lorrielau Thank you for raising this issue. yes, original yurt-tunnel tutorial doc has been deleted in this pull request: https://github.com/openyurtio/openyurt/pull/841/files#diff-96f02b2a66c1005bdf8a3b8367912ca0e8b5737279a607a511017fbe38569436.

Would you be able to fix yurt-tunnel error in manually-setup doc?

**Comment by lorrielau** [comment]
Sure thing.
@lorrielau

**Comment by lorrielau** [comment]
[As can be seen in this pr.](https://github.com/openyurtio/openyurt.io/pull/146)
