### ISSUE TITLE
[New Feature] If openyurt website need AOS animations for enhanced scroll effects .I can try to pull request

### ISSUE THREAD

**Issue by LofiSu** [openyurtio/openyurt.io#441]
Add AOS animations for https://openyurt.io/

Applied animations to various sections of the site
Improved user experience with smooth scroll effects
just like:
https://streampark.apache.org/zh-CN/
https://[michalsnik.github.io](https://michalsnik.github.io/aos/)/aos/

**Comment by rambohe-ch** [comment]
@LofiSu Thank you for your excellent suggestion. Integrating AOS animations can indeed enhance the user experience on https://openyurt.io/ by making the website more interactive and visually appealing.

Could you please proceed by creating a pull request with the necessary modifications? If you need any assistance or further clarification on the project, feel free to reach out me.

**Comment by LofiSu** [comment]
> @LofiSu Thank you for your excellent suggestion. Integrating AOS animations can indeed enhance the user experience on https://openyurt.io/ by making the website more interactive and visually appealing.
> 
> Could you please proceed by creating a pull request with the necessary modifications? If you need any assistance or further clarification on the project, feel free to reach out me.

Thanks，do u have WeChat.Or is there a communication group?

**Comment by rambohe-ch** [comment]
> > @LofiSu Thank you for your excellent suggestion. Integrating AOS animations can indeed enhance the user experience on https://openyurt.io/ by making the website more interactive and visually appealing.
> > Could you please proceed by creating a pull request with the necessary modifications? If you need any assistance or further clarification on the project, feel free to reach out me.
> 
> Thanks，do u have WeChat.Or is there a communication group?

@LofiSu Thank you for your reply, you can find the contact info here: https://github.com/openyurtio/openyurt?tab=readme-ov-file#contact

**Comment by LofiSu** [comment]
> > > @LofiSu Thank you for your excellent suggestion. Integrating AOS animations can indeed enhance the user experience on https://openyurt.io/ by making the website more interactive and visually appealing.
> > > Could you please proceed by creating a pull request with the necessary modifications? If you need any assistance or further clarification on the project, feel free to reach out me.
> > 
> > 
> > Thanks，do u have WeChat.Or is there a communication group?
> 
> @LofiSu Thank you for your reply, you can find the contact info here: https://github.com/openyurtio/openyurt?tab=readme-ov-file#contact

Hello, can you take a look at the PR I submitted?

**Comment by rambohe-ch** [comment]
@LofiSu Pull request #442  has been merged, so i will close this issue.
