### ISSUE TITLE
群二维码过期了可以置顶一个吗？

### ISSUE THREAD

**Issue by LofiSu** [openyurtio/openyurt.io#448]
虽然js也可以，但是为什么不用jsx呢？
![image](https://github.com/user-attachments/assets/227701d6-59a7-41b2-9e2b-a239dbeb7fb2)

**Comment by luc99hen** [comment]
应该只是当时维护人的偏好，欢迎提交PR优化下这里

**Comment by LofiSu** [comment]
> 应该只是当时维护人的偏好，欢迎提交PR优化下这里

群二维码过期了可以置顶一个吗？

**Comment by luc99hen** [comment]
@rambohe-ch 
> 
> 群二维码过期了可以置顶一个吗？

**Comment by rambohe-ch** [comment]
> > 应该只是当时维护人的偏好，欢迎提交PR优化下这里
> 
> 群二维码过期了可以置顶一个吗？

@LofiSu Sorry, I don't get the meaning which QR code is out of date, Would you like to give me the link of the QR code?

**Comment by LofiSu** [comment]
> > > 应该只是当时维护人的偏好，欢迎提交PR优化下这里
> > 
> > 
> > 群二维码过期了可以置顶一个吗？
> 
> @LofiSu Sorry, I don't get the meaning which QR code is out of date, Would you like to give me the link of the QR code?

https://github.com/openyurtio/openyurt这里的

**Comment by rambohe-ch** [comment]
@LofiSu QR code of OpenYurt dingding group has been upgraded, please enjoy it. i will close this issue.
